MENU_VARIANT_SANDBOX=y
MENU_GTEST=y
MENU_GMOCK=y

#
# GoogleTest Framework Settings
#
# end of GoogleTest Framework Settings

MENU_TESTING=y

#
# Unit Tests
#
MENU_TEST_PLAT_BYTESWAP=y
MENU_TEST_PLAT_BITREVERSE=y
MENU_TEST_PLAT_MEMFILL=y
MENU_TEST_PLAT_UNALIGNED=y

#
# Algorithm Unit Tests
#
MENU_TEST_ALGO_CRC32_LF=y
MENU_TEST_ALGO_CRC16_LF=y
MENU_TEST_ALGO_CRC32_IEEE=y
MENU_TEST_ALGO_CRC16_MODBUS=y
MENU_TEST_ALGO_SHA256=y
# end of Algorithm Unit Tests
# end of Unit Tests

#
# Algorithm
#
MENU_ALGO_CRC=y
MENU_ALGO_CRC_TABLE=y
# MENU_ALGO_CRC_LOOP is not set
MENU_ALGO_CRC32_LF=y
MENU_ALGO_CRC16_LF=y
MENU_ALGO_CRC32_TABLE_IEEE=y
MENU_ALGO_CRC16_TABLE_MODBUS=y
MENU_ALGO_CRC32_IEEE=y
MENU_ALGO_CRC16_MODBUS=y
MENU_ALGO_SHA256=y
# end of Algorithm

#
# Platform
#
# MENU_PLAT_NOCONTEND is not set
# MENU_PLAT_USE_CONTEND_FAIL is not set
MENU_PLAT_BYTESWAP=y
MENU_PLAT_BITREVERSE=y
MENU_PLAT_MEMFILL=y
MENU_PLAT_UNALIGNED=y
# end of Platform

#
# Protocol
#

#
# Utility
#
# MENU_UTIL_SOFTIRQ is not set
# end of Utility
