# recipe/sandbox/vairant.mk
CC := gcc -std=c99
CC += -Wall -Wextra -Wpedantic
CC += -g3 -Og
CC += -fsanitize=address
CC += -fsanitize=pointer-compare
CC += -fsanitize=pointer-subtract
CC += -fsanitize=leak
CC += -fsanitize=shift-exponent
CC += -fsanitize=shift-base
CC += -fsanitize=integer-divide-by-zero
CC += -fsanitize=unreachable
CC += -fsanitize=vla-bound
CC += -fsanitize=null
CC += -fsanitize=return
CC += -fsanitize=signed-integer-overflow
CC += -fsanitize=bounds
CC += -fsanitize=bounds-strict
CC += -fsanitize=alignment
CC += -fsanitize=object-size
CC += -fsanitize=float-cast-overflow
CC += -fsanitize=bool
CC += -fsanitize=enum
CC += -fsanitize=vptr
CC += -fsanitize=pointer-overflow
CC += -fsanitize=builtin
CC += -fsanitize-address-use-after-scope
CC += -fcf-protection=full
CC += -fstack-protector-all
CC += -fstack-check=specific
CC += -fprofile-arcs -ftest-coverage
CC += $(DEFS-y:%=-D%)
CC += $(INCS-y:%=-I%)

CPP := g++ -std=c++17
CPP += -Wall -Wextra -Wpedantic
CPP += -g3 -Og
CPP += -fsanitize=address
CPP += -fsanitize=pointer-compare
CPP += -fsanitize=pointer-subtract
CPP += -fsanitize=leak
CPP += -fsanitize=shift-exponent
CPP += -fsanitize=shift-base
CPP += -fsanitize=integer-divide-by-zero
CPP += -fsanitize=unreachable
CPP += -fsanitize=vla-bound
CPP += -fsanitize=null
CPP += -fsanitize=return
CPP += -fsanitize=signed-integer-overflow
CPP += -fsanitize=bounds
CPP += -fsanitize=bounds-strict
CPP += -fsanitize=alignment
CPP += -fsanitize=object-size
CPP += -fsanitize=float-cast-overflow
CPP += -fsanitize=bool
CPP += -fsanitize=enum
CPP += -fsanitize=vptr
CPP += -fsanitize=pointer-overflow
CPP += -fsanitize=builtin
CPP += -fsanitize-address-use-after-scope
CPP += -fcf-protection=full
CPP += -fstack-protector-all
CPP += -fstack-check=specific
CPP += -fprofile-arcs -ftest-coverage
CPP += $(DEFS-y:%=-D%)
CPP += $(CPPDEFS-y:%=-D%)
CPP += $(INCS-y:%=-I%)

LD := g++
LD += -g3 -Og
LD += -fsanitize=address
LD += -fsanitize=pointer-compare
LD += -fsanitize=pointer-subtract
LD += -fsanitize=leak
LD += -fsanitize=shift-exponent
LD += -fsanitize=shift-base
LD += -fsanitize=integer-divide-by-zero
LD += -fsanitize=unreachable
LD += -fsanitize=vla-bound
LD += -fsanitize=null
LD += -fsanitize=return
LD += -fsanitize=signed-integer-overflow
LD += -fsanitize=bounds
LD += -fsanitize=bounds-strict
LD += -fsanitize=alignment
LD += -fsanitize=object-size
LD += -fsanitize=float-cast-overflow
LD += -fsanitize=bool
LD += -fsanitize=enum
LD += -fsanitize=vptr
LD += -fsanitize=pointer-overflow
LD += -fsanitize=builtin
LD += -fsanitize-address-use-after-scope
LD += -fcf-protection=full
LD += -fstack-protector-all
LD += -fstack-check=specific
LD += -fprofile-arcs -ftest-coverage
LD += $(LDLIBS-y:%=-l%)

OBJ_TREE := $(SRC_TREE:%=$(D_BUILD)/%.o)
COVERAGE := platform
COVERAGE += algorithm
COVERAGE += utility

# header file dependencies generated by compiler
-include $(OBJ_TREE:%.o=%.d)

$(D_BUILD)/test-runner: $(OBJ_TREE) | $(OBJDIR_TREE)
	$(LD) -o $@ $(OBJ_TREE)

$(D_BUILD)/%.c.o: %.c | $(OBJDIR_TREE)
	$(CC) -c -MMD -MP -MF $(@:%.o=%.d) -MT $@ -o $@ $<

$(D_BUILD)/%.cc.o: %.cc | $(OBJDIR_TREE)
	$(CPP) -c -MMD -MP -MF $(@:%.o=%.d) -MT $@ -o $@ $<



#
# The following 2 targets are invoked by Eclipse CDT scanner discovery to print compiler include
# paths and predefined macros which are then parsed by Eclipse for source code indexing and
# run-as-you-type syntax checks.
#
.PHONY: specs/gcc
specs/gcc:
	$(CC) $(SPEC_FLAGS) -E -P -v -dD $(SPEC_INPUTS)

.PHONY: specs/g++
specs/g++:
	$(CPP) $(SPEC_FLAGS) -E -P -v -dD $(SPEC_INPUTS)



.PHONY: help
help: basic-help
	$(ECHO) $(call HELP_ITEM,variant,Makes and runs test-runner)
	$(ECHO) $(call HELP_ITEM,$(D_BUILD)/test-runner,Makes test-runner)
	$(ECHO) $(call HELP_ITEM,coverage,Makes coverage report)
	$(ECHO) $(call HELP_ITEM,test-report,Makes XML test report)

.PHONY: variant
variant: $(D_BUILD)/test-runner
	$(D_BUILD)/test-runner

.PHONY: coverage
coverage: $(D_BUILD)/coverage/index.html

.PHONY: test-report
test-report: $(D_BUILD)/test-report.xml

$(D_BUILD)/test-report.xml: $(D_BUILD)/test-runner
	$(D_BUILD)/test-runner --gtest_output=xml:$@

$(D_BUILD)/coverage.info: D_COVERAGE := $(D_BUILD)/$(D_SRC)
$(D_BUILD)/coverage.info: $(D_BUILD)/test-report.xml
	geninfo -b . --no-external -o $@ $(COVERAGE:%=$(D_COVERAGE)/%)

$(D_BUILD)/coverage:
	$(MKDIR) $@

$(D_BUILD)/coverage/index.html: $(D_BUILD)/coverage.info | $(D_BUILD)/coverage
	genhtml $< --output-directory $(@D)
