# source/googletest/subdir.mk
SRC-$(MENU_GTEST) += gtest.cc
SRC-$(MENU_GTEST) += gtest-death-test.cc
SRC-$(MENU_GTEST) += gtest-filepath.cc
SRC-$(MENU_GTEST) += gtest-port.cc
SRC-$(MENU_GTEST) += gtest-printers.cc
SRC-$(MENU_GTEST) += gtest-test-part.cc
SRC-$(MENU_GTEST) += gtest-typed-test.cc
SRC-$(MENU_GTEST) += gtest-matchers.cc
# GMock has its own main() function
# include the main() function from GTest only if not building GMock
ifneq ($(MENU_GMOCK),y)
SRC-$(MENU_GTEST) += gtest_main.cc
endif
SRC-$(MENU_GMOCK) += gmock_main.cc
SRC-$(MENU_GMOCK) += gmock.cc
SRC-$(MENU_GMOCK) += gmock-cardinalities.cc
SRC-$(MENU_GMOCK) += gmock-internal-utils.cc
SRC-$(MENU_GMOCK) += gmock-matchers.cc
SRC-$(MENU_GMOCK) += gmock-spec-builders.cc

CPPDEFS-$(MENU_GTEST_HASCLONE_1) += GTEST_HAS_CLONE=1
CPPDEFS-$(MENU_GTEST_HASCLONE_0) += GTEST_HAS_CLONE=0
CPPDEFS-$(MENU_GTEST_HASEXCEPTIONS_1) += GTEST_HAS_EXCEPTIONS=1
CPPDEFS-$(MENU_GTEST_HASEXCEPTIONS_0) += GTEST_HAS_EXCEPTIONS=0
CPPDEFS-$(MENU_GTEST_HASPOSIX_RE_1) += GTEST_HAS_POSIX_RE=1
CPPDEFS-$(MENU_GTEST_HASPOSIX_RE_0) += GTEST_HAS_POSIX_RE=0
CPPDEFS-$(MENU_GTEST_HASPTHREAD_1) += GTEST_HAS_PTHREAD=1
CPPDEFS-$(MENU_GTEST_HASPTHREAD_0) += GTEST_HAS_PTHREAD=0
CPPDEFS-$(MENU_GTEST_HASRTTI_1) += GTEST_HAS_RTTI=1
CPPDEFS-$(MENU_GTEST_HASRTTI_0) += GTEST_HAS_RTTI=0
CPPDEFS-$(MENU_GTEST_HASSTDWSTRING_1) += GTEST_HAS_STD_WSTRING=1
CPPDEFS-$(MENU_GTEST_HASSTDWSTRING_0) += GTEST_HAS_STD_WSTRING=0
CPPDEFS-$(MENU_GTEST_HASSEH_1) += GTEST_HAS_SEH=1
CPPDEFS-$(MENU_GTEST_HASSEH_0) += GTEST_HAS_SEH=0
CPPDEFS-$(MENU_GTEST_HASSTREAMREDIRECTION_1) += GTEST_HAS_STREAM_REDIRECTION=1
CPPDEFS-$(MENU_GTEST_HASSTREAMREDIRECTION_0) += GTEST_HAS_STREAM_REDIRECTION=0
CPPDEFS-$(MENU_GTEST_LINKEDASSHAREDLIBRARY_1) += GTEST_LINKED_AS_SHARED_LIBRARY=1
CPPDEFS-$(MENU_GTEST_LINKEDASSHAREDLIBRARY_0) += GTEST_LINKED_AS_SHARED_LIBRARY=0
CPPDEFS-$(MENU_GTEST_CREATESHAREDLIBRARY_1) += GTEST_CREATE_SHARED_LIBRARY=1
CPPDEFS-$(MENU_GTEST_CREATESHAREDLIBRARY_0) += GTEST_CREATE_SHARED_LIBRARY=0
CPPDEFS-$(MENU_GTEST_DEFAULTDETAHTEST_THREADSAFE) += GTEST_DEFAULT_DEATH_TEST_STYLE=\"threadsafe\"
CPPDEFS-$(MENU_GTEST_DEFAULTDETAHTEST_FAST) += GTEST_DEFAULT_DEATH_TEST_STYLE=\"fast\"
