# source/platform/subdir.mk
DEFS-$(MENU_PLAT_NOCONTEND) += CONFIG_NOCONTEND=1
DEFS-$(MENU_PLAT_USE_CONTEND_FAIL) += CONFIG_USE_CONTEND_FAIL=1
DEFS-$(MENU_PLAT_NOASSERT) += CONFIG_NOASSERT=1
DEFS-$(MENU_PLAT_ENDIAN_BIG) += CONFIG_ENDIAN=ENDIAN_BIG
DEFS-$(MENU_PLAT_ENDIAN_LITTLE) += CONFIG_ENDIAN=ENDIAN_LITTLE
DEFS-$(MENU_PLAT_ENDIAN_PDP) += CONFIG_ENDIAN=ENDIAN_PDP
DEFS-$(MENU_PLAT_ENDIAN_HS316) += CONFIG_ENDIAN=ENDIAN_HS316

SRC-$(MENU_PLAT_BYTESWAP) += byteswap.c

ifneq ($(MENU_PLAT_BYTESWAP_NOGENERIC),y)
SRC-$(MENU_PLAT_BYTESWAP) += byteswap-generic.c
endif
