# source/platform/posixos/subdir.mk
SRC-$(MENU_PLAT_POSIXOS_LOGGER) += logger.c
DEFS-$(MENU_PLAT_POSIXOS_LOGGER_LEVELTRACE) += CONFIG_LOGGER_LEVELTRACE=1
DEFS-$(MENU_PLAT_POSIXOS_LOGGER_LEVELDEBUG) += CONFIG_LOGGER_LEVELDEBUG=1
DEFS-$(MENU_PLAT_POSIXOS_LOGGER_LEVELINFO) += CONFIG_LOGGER_LEVELINFO=1
DEFS-$(MENU_PLAT_POSIXOS_LOGGER_LEVELERR) += CONFIG_LOGGER_LEVELERR=1
DEFS-$(MENU_PLAT_POSIXOS_LOGGER_LEVELCRIT) += CONFIG_LOGGER_LEVELCRIT=1
DEFS-$(MENU_PLAT_POSIXOS_LOGGER_LEVELDISABLE) += CONFIG_LOGGER_LEVELDISABLE=1
ifneq ($(MENU_PLAT_POSIXOS_LOGGER_FILEPATH),"")
DEFS-y += CONFIG_LOGGER_PATH=$(patsubst "%",\"%\",$(MENU_PLAT_POSIXOS_LOGGER_FILEPATH))
endif
